package com.yalco.estore.entity.enums;

public enum ProductCategoryType {
    COMPUTER_PERIPHERY,
    AUTO_ELECTRONICS,
    SMALL_APPLIANCES,
    AIR_CONDITIONER,
    PERSONAL_CARE,
    REFRIGERATOR,
    ELECTRONICS,
    SMART_PHONE,
    AUTOMOTIVE,
    AUTO_TYRES,
    DISHWASHER,
    COMPUTERS,
    LAUNDRY,
    PRINTER,
    BOILER,
    TABLET,
    GARDEN,
    GAMING,
    LAPTOP,
    SPORTS,
    AUDIO,
    BOOKS,
    DRYER,
    PHOTO,
    VIDEO,
    HOME,
    TOYS,
    TV
}
